package com.practice.Executor;

import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

public class CallDoThings {

	public static void main(String[] args) {
		ExecutorService s = Executors.newCachedThreadPool();
		//int abfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffabfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff=2;
		
		
		int aa;
		int AA;
		///bhjhgjghjvhj
		
		long ssn =222_333;
		
		for(int i=0;i<10;i++) {
			s.submit(new DoThings());
			
		}
		
		s.shutdownNow();
	}
	

}
